### ISSUE TITLE
Package name is misleading

### ISSUE THREAD

**Issue by joshdifabio** [kelunik/loop-block#1]
When I saw this repo on my news feed I assumed this would be some kind of `await($loop, $promise)` implementation. Maybe the package name could be changed to better describe what this is about? Maybe _loop-block-detector_ or something like that? Feel free to ignore & close.

**Comment by kelunik** [comment]
There will be a separate package like `loop-wait`or so that handles that. Leaving open for now for other suggestions, but I don't like too long names, hence also not `event-loop-block`.
